version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cyoa-postgres
    environment:
      POSTGRES_DB: cyoa_litrpg
      POSTGRES_USER: cyoa_user
      POSTGRES_PASSWORD: cyoa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
